webtalk_init -webtalk_dir /home/krzeslaav/SEM_1/sdup_project/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/fft_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May 29 16:19:18 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2c571c19-4160-4279-9d28-709a6a75abac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b1b06dbd3604ccfa2b88d09c5c6691f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.069 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "5" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "40 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "5 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "53" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "205864_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2469348552 -regid "" -xml /home/krzeslaav/SEM_1/sdup_project/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/fft_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/krzeslaav/SEM_1/sdup_project/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/fft_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/krzeslaav/SEM_1/sdup_project/vivado/vivado.sim/sim_1/behav/xsim/xsim.dir/fft_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
