# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_zynq_ultra_ps_e_0_0/main_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==main_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_dma_0_0/main_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_dma_0_0 || ORIG_REF_NAME==main_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_stft_axis_wrapper_0_0/main_design_stft_axis_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_stft_axis_wrapper_0_0 || ORIG_REF_NAME==main_design_stft_axis_wrapper_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_gpio_0_0/main_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_gpio_0_0 || ORIG_REF_NAME==main_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_smc_0/main_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_smc_0 || ORIG_REF_NAME==main_design_axi_smc_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_ps8_0_99M_0 || ORIG_REF_NAME==main_design_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_smc_1_0/main_design_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_smc_1_0 || ORIG_REF_NAME==main_design_axi_smc_1_0} -quiet] -quiet

# XDC: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/main_design_ooc.xdc
