# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.runs/synth_1/main_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param physdb.placeDBImplUsesPlaceStorage 0
set_param bd.open.in_stealth_mode 2
set_param chipscope.maxJobs 1
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.cache/wt [current_project]
set_property parent.project_path /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property ip_repo_paths /home/krzeslaav/SEM_1/sdup_project/STFT_IP_PACKAGE [current_project]
update_ip_catalog
set_property ip_output_repo /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/hdl/main_design_wrapper.v
add_files /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.srcs/sources_1/bd/main_design/main_design.bd
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_zynq_ultra_ps_e_0_0/main_design_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_zynq_ultra_ps_e_0_0/main_design_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_dma_0_0/main_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_dma_0_0/main_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_dma_0_0/main_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_gpio_0_0/main_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_gpio_0_0/main_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_1/bd_ad5e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_2/bd_ad5e_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_3/bd_ad5e_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_4/bd_ad5e_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_5/bd_ad5e_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_6/bd_ad5e_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_7/bd_ad5e_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_8/bd_ad5e_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_9/bd_ad5e_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_10/bd_ad5e_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_11/bd_ad5e_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_12/bd_ad5e_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_13/bd_ad5e_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_14/bd_ad5e_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_15/bd_ad5e_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_16/bd_ad5e_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_20/bd_ad5e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_21/bd_ad5e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_22/bd_ad5e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_23/bd_ad5e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_24/bd_ad5e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_25/bd_ad5e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_29/bd_ad5e_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_30/bd_ad5e_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_31/bd_ad5e_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_32/bd_ad5e_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_33/bd_ad5e_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_34/bd_ad5e_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_35/bd_ad5e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_36/bd_ad5e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_37/bd_ad5e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_38/bd_ad5e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_39/bd_ad5e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_40/bd_ad5e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_42/bd_ad5e_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_43/bd_ad5e_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_44/bd_ad5e_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_45/bd_ad5e_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_46/bd_ad5e_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/bd_0/ip/ip_47/bd_ad5e_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_1/bd_f991_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_2/bd_f991_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_3/bd_f991_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_4/bd_f991_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_5/bd_f991_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_6/bd_f991_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_10/bd_f991_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_11/bd_f991_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_12/bd_f991_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_16/bd_f991_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_17/bd_f991_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_18/bd_f991_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_19/bd_f991_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_20/bd_f991_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_21/bd_f991_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_22/bd_f991_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_23/bd_f991_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_24/bd_f991_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/bd_0/ip/ip_25/bd_f991_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_axi_smc_1_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/main_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.srcs/utils_1/imports/synth_1/stft_axis_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main_design_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file main_design_wrapper_utilization_synth.rpt -pb main_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
