# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.srcs/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0.xci
# IP: The module: 'main_design_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.srcs/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0.xci
# IP: The module: 'main_design_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krzeslaav/SEM_1/sdup_project/STFT_FPGA/stft_v1.0.gen/sources_1/bd/main_design/ip/main_design_rst_ps8_0_99M_0/main_design_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
